build.gradle
charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.preview.template.yaml
database/Dockerfile
database/init-db.sh
docker-compose.yml
src/main/resources/application.yaml
src/main/resources/db/migration/V1_1__init_tables.sql

https://tools.hmcts.net/jira/browse/RDCC-1868
feat: Create Database of the org urn microservice(RDCC-1868)
No

feat: Create Database of the org urn microservice(RDCC-1868)

---

build.gradle
charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.yaml

https://tools.hmcts.net/jira/browse/RDCC-1912
fix:Bum up Spring version for CVE
No

fix:Bum up Spring version for CVE

---

infrastructure/main.tf
infrastructure/provider.tf
infrastructure/state.tf
infrastructure/terraform.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/RDCC-1911
```
[ ] Yes
[X] No
```

TF upgrade to 0.12.16 and Azure RM upgrade to 2.20.0 - Master

---

Jenkinsfile_CNP

NA
fix:master build fix for enableDbMigration
No

fix:master build fix for enableDbMigration

---

build.gradle

RDCC-1933
This PR is to cover the bump ups and owasp changes
```
[ ] Yes
[ X] No
```

Fix : Bump up and owasp update(RDCC-1933)

---

build.gradle

NA
fix: reverting postgres version
No

fix: reverting postgres version

---

src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql

https://tools.hmcts.net/jira/browse/RDCC-1927
refactor: updated audit and exception table logging LRD (RDCC-1927)
No

refactor: updated audit and exception table logging LRD (RDCC-1927)

---

charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.yaml

feat:correcting the image name
```
[ ] Yes
[X] No
```

feat:correcting the image name

---

Jenkinsfile_nightly
README.md
audit.json

feat: fixing the security scan
```
[ ] Yes
[X] No
```

feat:added for security scan

---

build.gradle
src/test/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositoryTest.java

NA
fix: JPA mock repository test in Junit #98
No

fix: JPA mock repository test in Junit

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-1966
Whitelisting Fee and Payment Service so that they can access the LRD API
```
[ ] Yes
[x] No
```

RDCC-1966: adding 'payment_app' to whitelist

---

.travis.yml
Dockerfile
charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/requirements.yaml
gradle/wrapper/gradle-wrapper.properties
src/contractTest/java/uk/gov/hmcts/reform/lrdapi/IdamConsumerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/LrdApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/JwtTokenUtil.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/KeyGenUtil.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Jurisdiction.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssoc.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/lrdapi/oidc/JwtGrantedAuthoritiesConverterTest.java

https://tools.hmcts.net/jira/browse/RDCC-2033
Updating java chart version - Master
```
[ ] Yes
[X] No
```

Updating java chart version - Master

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDCC-2044
```
[ ] Yes
[X] No
```

Add secrets required by the pipeline - ITHC

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDCC-2044
```
[ ] Yes
[X] No
```

Add secrets required by the pipeline - PerfTest

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDCC-2044
```
[ ] Yes
[X] No
```

Add secrets required by the pipeline - Master

---

src/main/java/uk/gov/hmcts/reform/lrdapi/LrdApiApplication.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Jurisdiction.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/OrgBusinessArea.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/OrgSubBusinessArea.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/OrgUnit.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Service.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssoc.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdOrgInfoServiceResponseTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssocTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImplTest.java

feat: fixing the code review comments
```
[ ] Yes
[X] No
```

feat:removing EnableCircuitBreaker and correcting other mappings

---

Jenkinsfile_CNP
Jenkinsfile_nightly
build.gradle
charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.preview.template.yaml
charts/rd-location-ref-api/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/CustomSerenityRunner.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/ToggleEnable.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/LrdAuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
src/integrationTest/resources/application-test.yml
src/main/java/uk/gov/hmcts/reform/lrdapi/config/LaunchDarklyConfiguration.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/ExceptionMapper.java
src/main/java/uk/gov/hmcts/reform/lrdapi/exception/ForbiddenException.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/FeatureToggleService.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluation.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yml
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/ExceptionMapperTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluationTest.java

https://tools.hmcts.net/jira/browse/RDCC-2011
refactor: toggle off  LRD API (RDCC-2011)
No

refactor: toggle off  LRD API (RDCC-2011)

---

build.gradle

fix: flyway schema

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/CustomSerenityRunner.java
src/main/java/uk/gov/hmcts/reform/lrdapi/config/LaunchDarklyConfiguration.java

N/A
Correcting service name in CustomSerenityRunner
```
[ ] Yes
[x] No
```

fix: Nightly Build fix

---

build.gradle

Upgraded versions to fix CVE-2020-13956 and CVE-2020-25638
```
[ ] Yes
[x] No
```

build: Upgraded versions to fix CVE-2020-13956 and CVE-2020-25638

---

build.gradle

RDCC-2017
This PR covers the Jar version upgrade
```
[ ] Yes
[ X] No
```

Bump : RDCC-2017 Jar version upgrade

---

build.gradle

RDCC-2017
This PR deals with Jar version upgrade
```
[ ] Yes
[ X] No
```

Bump : RDCC-2017 Upgrade Jar Versions

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-2143
RDCC-2143: CVE-2020-8908 fix
```
[ ] Yes
[x] No
```

RDCC-2143: CVE-2020-8908 fix

---

charts/rd-location-ref-api/values.preview.template.yaml
charts/rd-location-ref-api/values.yaml
infrastructure/main.tf
src/main/resources/bootstrap.yml

https://tools.hmcts.net/jira/browse/RDCC-2141
```
[ ] Yes
[X] No
```

Add s2s secret reference

---

audit.json
charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/requirements.yaml

https://tools.hmcts.net/jira/browse/RDCC-2462
Security scan reported issue fix
```
[ ] Yes
[x] No
```

fix: Security scan reported issue fix

---

charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.preview.template.yaml
charts/rd-location-ref-api/values.yaml
src/main/resources/bootstrap.yml

https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```

Change app insights secret name

---

build.gradle
config/owasp/suppressions.xml

NA
fix: Spring version upgrade for Tomcat CVE fix
No

fix: Spring version upgrade for Tomcat CVE fix

---

src/main/resources/application.yaml

RDCC-2632 Added loggers for hikari
RDCC-2632 Added loggers for hikari
```
[ ] Yes
[X] No
```

RDCC-2632 Added loggers for hikari

---

charts/rd-location-ref-api/Chart.yaml
src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/LrdApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
src/main/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositry.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/LrdService.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluation.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-2420
Rdcc 2420 get service code by ccdservicename
```
[ ] Yes
[x] No
```

Rdcc 2420 get service code by ccdservicename

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-2743
Fixed security scan reported issue
```
[ ] Yes
[x] No
```

fix: Security scan fix

---

build.gradle
src/smokeTest/java/uk/gov/hmcts/reform/lrdapi/SmokeTest.java

https://tools.hmcts.net/jira/browse/RDCC-2719
fix: Added locations in gradle for flyway
```
[ ] Yes
[x] No
```

fix: Added locations in gradle for flyway

---

Jenkinsfile_CNP

added demo branch in sync configuration

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssoc.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
src/test/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssocTest.java

RDCC-2766 changed response for duplicate issue
RDCC-2766 changed response for duplicate issue
```
[ ] Yes
[X] No
```

RDCC-2766 changed response for duplicate issue

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSPO-2842
Enable DB self service
```
[ ] Yes
[X] No
```

Enable DB self service

---

src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/ConstraintValidation.java
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerTest.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-2878
Change description
Added validations for special characters and whitespaces, the api call will return a 400 bad request response if  an invalid value that contains special character or spaces in between are passed in the request
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X] No

RDCC-2878 Added validations for special characters and whitespaces

---

Jenkinsfile_nightly

added serenity report config in nightly job

---

src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/LrdApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/GetBuildingLocationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
src/main/java/uk/gov/hmcts/reform/lrdapi/repository/BuildingLocationRepository.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/ILrdBuildingLocationService.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerGetBuildingLocationsTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceTest.java

https://tools.hmcts.net/jira/browse/RDCC-2949
- Added new query param `building_location_name` to the existing `/building-locations` to retrieve the building location details for a given building location name.
```
[ ] Yes
[x] No
```

feat: get particular building location details for a given building location name

---

audit.json
security.sh

fixed the security scan in nightly job

---

src/main/resources/db/migration/V1_14__update_service_name_damages.sql

https://tools.hmcts.net/jira/browse/RDCC-3089
updated service name for AAA7 to Damages
```
[ ] Yes
[X] No
```

updated service name for AAA7 to Damages

---

build.gradle

RDCC-3141: fixed CVE

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-3109
https://tools.hmcts.net/jira/browse/RDCC-2885
added for s2s communication from jrd to lrd
```
[ ] Yes
[X] No
```

added for s2s communication from jrd to lrd

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3150
Update repositories reference to Jitpack
```
[ ] Yes
[X] No
```

RDCC-3150 - Update repositories reference to Jitpack

---

audit.json
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java

https://tools.hmcts.net/jira/browse/RDCC-3012
Nightly build failure fix
```
[ ] Yes
[x] No
```

fix: Security scan reported issue

---

charts/rd-location-ref-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-3169
Update chart versions in all PRD repos
```
[ ] Yes
[X] No
```

RDCC-3169 -Update chart versions in all PRD repos

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3237
Ref Data - Fix CVE issue : CVE-2021-28170
```
[ ] Yes
[X] No
```

RDCC-3237- Fix CVE issue : CVE-2021-28170

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3239
Fix CVE issues CVE-2021-22119
```
[ ] Yes
[X] No
```

RDCC-3237 - Fix CVE issues CVE-2021-22119

---

config/owasp/suppressions.xml

fixed dependency check issue

---

src/main/resources/db/migration/V1_15__alter_dataload_exception_records_add_row_id.sql

https://tools.hmcts.net/jira/browse/RDCC-3230
Added flyway script to include row_id column in the exception table
```
[ ] Yes
[x] No
```

feat: RDCC-3230 Added flyway script to include row_id column in the exception table

---

Jenkinsfile_CNP
Jenkinsfile_nightly
README.md
charts/rd-location-ref-api/values.preview.template.yaml
charts/rd-location-ref-api/values.yaml
src/functionalTest/resources/application-functional.yaml
src/integrationTest/resources/application-test.yml
src/main/resources/application.yaml

RDCC-3277
RDCC-3277
```
[ ] Yes
[X] No
```

RDCC-3277 removing hardcoded config values

---

audit.json
build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3557
CVE-2021-22096 by upgrading springboot version to 2.4.12
```
[ ] Yes
[x] No
```

fix: CVE-2021-22096 by upgrading springboot version to 2.4.12

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3644
Extended CVE suppression
```
[ ] Yes
[x] No
```

RDCC-3644: LRD CVE suppression extension

---

Jenkinsfile_CNP
Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3681
Publish test reports in Jenkins
```
[ ] Yes
[ ] No
```

RDCC-3681-Publish test reports in Jenkins

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/IntegrationTestOidcSecurityConfig.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/RegionServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-3616
Added unit tests to increase mutation test coverage
```
[ ] Yes
[x] No
```

RDCC-3616: LRD - increase mutation coverage

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/SerenityTestWithoutReporting.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/counter/TestCountListener.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/counter/TestCounter.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityExtension.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityPageExtension.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/SerenityPageExtension.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/TestConfiguration.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/TestMethodAnnotations.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/guice/JUnit5Module.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/guice/JUnitInjectors.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/IntegrationTestOidcSecurityConfig.java
src/main/java/uk/gov/hmcts/reform/lrdapi/config/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdOrgInfoServiceResponse.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-3620
Replaced deprecated methods and refactored code
```
[ ] Yes
[x] No
```

RDCC-3620: LRD Code refactoring to implement Java11 features

---

.dependabot/config.yml
.github/dependabot.yml
build.gradle

Changes made to fix bot PRs
```
[ ] Yes
[x ] No
```

Feat:Changes made to fix bot PRs

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3782
Changes made to fix botPR issues
```
[ ] Yes
[ x] No
```

Feat:RD - Review, Approve & Merge Bot PR's

---

Jenkinsfile_nightly

*### JIRA link ###
https://tools.hmcts.net/jira/browse/RDCC-3840
Enabled fortify scan
```
[ ] Yes
[x] No
```

fix: RDCC-3840 Enabled fortify scan

---

src/main/resources/db/migration/V1_17__alter_court_venue_table.sql

https://tools.hmcts.net/jira/browse/RDCC-3846
Add new columns to table "Court_Venue"
```
[ ] Yes
[X] No
```

Feature: add new columns to table "Court_Venue"

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3923
Removed deprecated jcenter repository
```
[ ] Yes
[x] No
```

RDCC-3923: LRD-api Remove Deprecated Jcenter Repository

---

src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenueResponse.java
src/main/java/uk/gov/hmcts/reform/lrdapi/oidc/JwtGrantedAuthoritiesConverter.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
src/test/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtilsTest.java

https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[ X] No
```

fixed sonar issues

---

src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceTest.java

https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[X] No
```

fixed sonar issues - @ParameterizedTest

---

src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/GetBuildingLocationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_17__alter_court_venue_table.sql
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenueResponse.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/CourtVenue.java
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenueResponseTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-3851
LRD : Changes to API response of the Location categories API
```
[ ] Yes
[X] No
```

Rdcc 3851 service code

---

charts/rd-location-ref-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.3
```
[ ] Yes
[x] No
```

fix: Updated java chart version to 3.7.3

---

src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_18__alter_tables_add_columns.sql
src/main/resources/db/migration/V1_18__alter_tables_add_columns.sql

https://tools.hmcts.net/jira/browse/RDCC-4143
LRD : Update the response of the Building Location API for HMC requirements
```
[ ] Yes
[ x] No
```

Feat:Update the response of the Building Location API for HMC requirements

---

src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/WireMockExtension.java

https://tools.hmcts.net/jira/browse/RDCC-4301
Updated Wiremock call settings
```
[ ] Yes
[x] No
```

RDCC-4301: LRD API - Improve integration test case timings

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4331
```
[ ] Yes
[X] No
```

Rdcc 4331-LRD CVE CVE-2020-36518

---

src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Service.java

https://tools.hmcts.net/jira/browse/RDCC-2284
Performance Test - LRD DB - Repeat requests observed
```
[ ] Yes
[ x] No
```

Feat:Performance Test - LRD DB - Repeat requests observed

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Service.java

https://tools.hmcts.net/jira/browse/RDCC-2284
Performance Test - LRD DB - Repeat requests observed
```
[ ] Yes
[ x] No
```

Feat: LRD DB - Repeat requests observed

---

build.gradle

updated postgresql

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4504
fix for CVE-2022-22968
```
[ ] Yes
[X] No
```

LRD-Nightly build failure -25/04/2022

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluation.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java

h[ttps://tools.hmcts.net/jira/browse/RDCC-4504](https://tools.hmcts.net/jira/browse/RDCC-4523)
JIRA link (if applicable)
LRD Api : Induce Common Libs library in to Location Reference Data API by removing unwanted dependencies
Change description
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

RDCC-4523 LRD Api : Induce Common Libs library in to Location Reference Data API by removing unwanted dependencies

---

src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueController.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenuesByServiceCodeResponse.java
src/main/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssoc.java
src/main/java/uk/gov/hmcts/reform/lrdapi/oidc/JwtGrantedAuthoritiesConverter.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/RegionServiceImpl.java
src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java

h[ttps://tools.hmcts.net/jira/browse/RDCC-4523](https://tools.hmcts.net/jira/browse/RDCC-4523)
JIRA link (if applicable)
LRD Api : Induce Common Libs library in to Location Reference Data API by removing unwanted dependencies
Change description
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

RDCC-4523 Sonar Issues Fixes

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4633
```
[ ] Yes
[X] No
```

Fix CVE CVE-2022-25647

---

Dockerfile
acb.tpl.yaml

https://tools.hmcts.net/jira/browse/RDCC-4717
Added multi-architecture ACR Task template
```
[ ] Yes
[x] No
```

feat: Added multi-architecture ACR Task template

---

renovate.json

https://tools.hmcts.net/jira/browse/RDCC-4798
Configured renovate
```
[ ] Yes
[x] No
```

config: RDCC-4798 Configured renovate

---

src/main/java/uk/gov/hmcts/reform/lrdapi/config/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/lrdapi/config/SecurityEndpointFilter.java
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/UnauthorizedException.java
src/main/java/uk/gov/hmcts/reform/lrdapi/repository/IdamRepository.java
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/UnauthorizedExceptionTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/repository/IdamRepositoryTest.java

https://tools.hmcts.net/jira/browse/RDCC-4680
To handle 500 HTTP responses
```
[ ] Yes
[x ] No
```

Feat:To handle 500 HTTP responses

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
src/main/resources/db/migration/V1_19__Insert_mrd_changes_records.sql

https://tools.hmcts.net/jira/browse/RDCC-4868
```
[ ] Yes
[X] No
```

LRD : Testing using MRD test files for Location Reference Data

---

src/main/resources/db/migration/V1_19__Insert_mrd_changes_records.sql

https://tools.hmcts.net/jira/browse/RDCC-4876
```
[ ] Yes
[X] No
```

RDCC-4876 : Testing using MRD test files for Location Reference Data

---

.github/dependabot.yml

https://tools.hmcts.net/jira/browse/RDCC-4909
Deleted dependabot yaml file as Renovate changes are already in place to upgrade the dependencies automatically
```
[ ] Yes
[x] No
```

RDCC-4898 Delete dependabot yaml file

---

charts/rd-location-ref-api/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-5007
Adding Suppression for `CVE-2022-34305`
```
[ ] Yes
[x] No
```

RDCC-5007: Adding Suppression for `CVE-2022-34305`

---

src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerOrgServiceTest.java

https://tools.hmcts.net/jira/browse/RDCC-5196
LRD orgservice api does not give response correctly
```
[ ] Yes
[X] No
```

RDCC-5196 service code to allow numbers

---

build.gradle
config/owasp/suppressions.xml

RDCC-5392: Adding suppression for CVE-2022-25857

---

src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
src/integrationTest/resources/db/testmigration/V1_21__update_Court_type_service_assoc.sql
src/integrationTest/resources/db/testmigration/V1_5__services.sql
src/main/resources/db/migration/V1_21__update_Court_type_service_assoc.sql

Added court_type_service_assoc record

---

src/main/resources/db/migration/V1_23__create_views.sql

committing Views
```
[ ] Yes
[X] No
```

Views commit

---

infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/variables.tf

Create Read Replica in Demo
```
[ ] Yes
[X] No
```

create read replica

---

infrastructure/prod.tfvars

creating database replica in production environment
JIRA link : creating database replica in production environment](https://tools.hmcts.net/jira/browse/RDCC-5622)
Change description : creating database replica in production environment
Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

creating replica database in prod environment

---

infrastructure/ithc.tfvars
infrastructure/perftest.tfvars

https://tools.hmcts.net/jira/browse/RDCC-5775
MI Reporting : Create Replica database for Locations in ITHC environment
```
[ ] Yes
[ X] No
```

creating read replica - ithc

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LocationRefApiPostgresqlContainer.java
src/integrationTest/resources/application-test.yml
src/integrationTest/resources/db/testmigration/V1_14__lrd_surrogate_key_changes.sql

https://tools.hmcts.net/jira/browse/RDCC-5784
Containerisation of integration test cases
```
[ ] Yes
[ x] No
```

Feat:Containerisation of integration test cases

---

charts/rd-location-ref-api/Chart.yaml
infrastructure/terraform.tf

https://tools.hmcts.net/jira/browse/RDCC-5894
```
[ ] Yes
[X] No
```

Upgrade Terraform and helm :: RDCC-5894

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/rd-location-ref-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-5931
Replace after with afterSuccess in all RD Repos
```
[ ] Yes
[X] No
```

Replace after with afterSuccess for deprecation : RDCC-5931

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-6259
```
[ ] Yes
[X] No
```

cve issue fix RDCC- 6259

---

src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/main/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositry.java
src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
src/main/resources/db/migrationAks/V2_1__service_to_ccd_case_type_assoc.sql
src/main/resources/db/postgres/V1_24__drop_indexes.sql
src/test/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImplTest.java

DROP INDEX
```
[ ] Yes
[X ] No
```

drop index

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java

https://tools.hmcts.net/jira/browse/RDCC-6414
[RDCC-6414]-Fix for Functional Test cases fail in AAT env
```
[ ] Yes
[ x] No
```

[RDCC-6414]-Fix for Functional Test cases fail in AAT env

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java

https://tools.hmcts.net/jira/browse/RDCC-6452
[RDCC-6452]Fix for failure of Nightly build
```
[ ] Yes
[ x] No
```

[RDCC-6452]Fix for failure of Nightly build

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/RDCC-6421
update renovate.json
```
[ ] Yes
[x] No
```

RDCC-6421- renovate.json update.

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java

Nightly build failure fix
```
[ ] Yes
[X] No
```

Nightly build failure due to expectation change

---

audit.json

https://tools.hmcts.net/jira/browse/DTSRD-202
Addresses nightly build failure
```
[ ] Yes
[x] No
```

Addresses night build failure

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSRD-327
Applied remedy from https://spring.io/security/cve-2021-22044
```
[ ] Yes
[x] No
```

Addressed CVE-2021-22044

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-550
fix CVE-2023-20883
```
[ ] Yes
[x] No
```

DTSRD-556: fix CVE-2023-20883

---

build.gradle
config/owasp/suppressions.xml

cve suppression   CVE-2023-34034

---

audit.json
src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/WelcomeController.java

DTSRD-1173
```
[ ] Yes
[ *] No
```

Dtsrd 1173

---

.github/renovate.json
renovate.json

- Upgrading renovate config.
https://tools.hmcts.net/jira/browse/DTSRD-1222
```
[ ] Yes
[x] No
```

DTSRD-1222

---

build.gradle
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

DTSRD-1252
```
[ ] Yes
[ *] No
```

DTSRD-1252.Upgrade Postgresdb to V15

---

build.gradle
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

DTSRD-1252
```
[ ] Yes
[ ] No
```

DTSRD-1252. Upgrade to Postgres V15 

---

infrastructure/pgsql-flexible-server.tf

Dtsrd 1252

---

Jenkinsfile_CNP

DTSRD-1466.
```
[ ] Yes
[ ] No
```

DTSRD-1466.Remove branches to sync -location demo and master

---

Jenkinsfile_CNP
build.gradle

DTSRD-1466
```
[ ] Yes
[ ] No
```

DTSRD-1466..Remove branches to sync -commondata demo 

---

infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

DTSRD-1250
```
[ ] Yes
[ ] No
```

DTSRD-1250 . Reverting V15 changes done to perftest

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

DTSRD-1253.adding v15 scripts to master and sync to all branches

---

build.gradle

Addresses CVE-2023-34055, CVE-2023-34053
```
[ ] Yes
[x] No
```

Addresses CVE-2023-34055, CVE-2023-34053

---

src/integrationTest/resources/application-test.yml

Upgrading perftest branch to V16 and adding subnet_suffix

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

DTSRD-1893.Upgrading main branch to V16 and adding subnet_suffix 

---

infrastructure/main.tf
infrastructure/variables.tf

Dtsrd 1252.Adding force_user_permissions_trigger to get DTS CFT DB Access Reader access

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/variables.tf

FIX AZURE EXTENSIONS

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/variables.tf

Fix azure extension-demo

---

infrastructure/variables.tf

Demo- fix azure extensions

---

charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.yaml

DTSRD-2442: PI33 Configure spot instances in non-production

---

build.gradle

Update pitest plugin

---

infrastructure/main.tf

FIX SCHEMA OWNERSHIP

---

infrastructure/main.tf

Update schema ownership

---

charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.yaml
infrastructure/main.tf
infrastructure/terraform.tf

DTSRD-2750.Deleting Single server from demo

---

charts/rd-location-ref-api/Chart.yaml
charts/rd-location-ref-api/values.yaml

Deleting Single server from demo

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSRD-2810
- updated hmcts java gradle plugin
- suppressions cleanup
```
[ ] Yes
[x] No
```

DTSRD-2810

---

gradle/wrapper/gradle-wrapper.properties
gradlew
src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/ContainerImageNameSubstitutor.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LocationRefApiPostgresqlContainer.java
src/main/resources/testcontainers.properties

PactVerification pending pacts

---

build.gradle

Trigger master pipeline

---

Dockerfile
acb.tpl.yaml
build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-3357
Java 21 upgrade
```
[ ] Yes
[x] No
```

DTSRD-3357

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-3477
Fix local DependencyCheck, version upgraded to 10.0.3
```
[ ] Yes
[x] No
```

DTSRD-3477 Fix local DependencyCheck, version upgraded to 10.0.3

---

.github/workflows/swagger.yml
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/config/SwaggerPublisherTest.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSRD-3562
Swagger Publishing
```
[ ] Yes
[x] No
```

DTSRD-3562 Swagger Publishing

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/DTSRD-3578
CVE-2024-22236
```
[ ] Yes
[x] No
```

DTSRD-3578

---

src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
src/main/resources/db/migration/V1_28__org_chart_updates.sql

https://tools.hmcts.net/jira/browse/DTSRD-3711
Org chart changes (changelog 151)
```
[ ] Yes
[x] No
```

DTSRD-3711

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CME-250
```
[ ] Yes
[ x] No
```

CME-250: Disable sync to ITHC for database monitoring testing

---

infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/CME-250
```
[ ] Yes
[ x] No
```

CME-250: Database monitoring and alerting on RD repositories

---

infrastructure/terraform.tf

https://tools.hmcts.net/jira/browse/CME-299
```
[ ] Yes
[ x] No
```

CME-299: Update azurerm

---

build.gradle
src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/LrdAuthorizationEnabledIntegrationTest.java

https://tools.hmcts.net/jira/browse/DTSRD-4065
```
[ ] Yes
[x] No
```

DTSRD-4065

---

charts/rd-location-ref-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CME-409
```
[ ] Yes
[ x] No
```

CME-409: Update OCI endpoint
